" Vim color file
<<<<<<< HEAD
"   This file was generated by Palette
"   http://rubygems.org/gems/palette
"
" Author: Compiled from a handful of different themes
" Notes:  Github color scheme (light)

hi clear
if version > 580
    if exists("syntax_on")
        syntax reset
    endif
endif

let colors_name="github"

if has("gui_running")
    set background=light
endif

hi Normal       guifg=#000000 ctermfg=16   guibg=#F8F8FF ctermbg=231  gui=NONE cterm=NONE
hi DiffAdd      guifg=#003300 ctermfg=22   guibg=#DDFFDD ctermbg=194  gui=NONE cterm=NONE
hi DiffChange   guibg=#ECECEC ctermbg=255  gui=NONE cterm=NONE
hi DiffText     guifg=#000033 ctermfg=17   guibg=#DDDDFF ctermbg=189  gui=NONE cterm=NONE
hi DiffDelete   guifg=#DDCCCC ctermfg=252  guibg=#FFDDDD ctermbg=224  gui=NONE cterm=NONE
hi Folded       guifg=#808080 ctermfg=244  guibg=#ECECEC ctermbg=255  gui=NONE cterm=NONE
hi LineNr       guifg=#BBBBBB ctermfg=250  guibg=#ECECEC ctermbg=255  gui=NONE cterm=NONE
hi NonText      guifg=#808080 ctermfg=244  guibg=#ECECEC ctermbg=255  gui=NONE cterm=NONE
hi VertSplit    guifg=#BBBBBB ctermfg=250  guibg=#BBBBBB ctermbg=250  gui=NONE cterm=NONE
hi StatusLine   guifg=#404040 ctermfg=238  guibg=#BBBBBB ctermbg=250  gui=BOLD cterm=BOLD
hi StatusLineNC guifg=#BBBBBB ctermfg=250  guibg=#ECECEC ctermbg=255  gui=ITALIC cterm=NONE
hi ModeMsg      guifg=#990000 ctermfg=88   gui=NONE cterm=NONE
hi MoreMsg      guifg=#990000 ctermfg=88   gui=NONE cterm=NONE
hi Title        guifg=#EF5939 ctermfg=203  gui=NONE cterm=NONE
hi WarningMsg   guifg=#EF5939 ctermfg=203  gui=NONE cterm=NONE
hi SpecialKey   guifg=#FFFFFF ctermfg=231  guibg=#FF1100 ctermbg=196  gui=ITALIC cterm=NONE
hi MatchParen   guifg=#000000 ctermfg=16   guibg=#CDCDFD ctermbg=189  gui=NONE cterm=NONE
hi Underlined   guifg=#000000 ctermfg=16   gui=UNDERLINE cterm=UNDERLINE
hi Directory    guifg=#990000 ctermfg=88   gui=NONE cterm=NONE
hi Visual       guifg=#FFFFFF ctermfg=231  guibg=#3465A4 ctermbg=61   gui=NONE cterm=NONE
hi VisualNOS    guifg=#FFFFFF ctermfg=231  guibg=#204A87 ctermbg=24   gui=NONE cterm=NONE
hi IncSearch    guifg=#000000 ctermfg=16   guibg=#CDCDFD ctermbg=189  gui=ITALIC cterm=NONE
hi Search       guifg=#000000 ctermfg=16   guibg=#CDCDFD ctermbg=189  gui=ITALIC cterm=NONE
hi Ignore       guifg=#808080 ctermfg=244  gui=NONE cterm=NONE
hi Identifier   guifg=#0086B3 ctermfg=31   gui=NONE cterm=NONE
hi PreProc      guifg=#A0A0A0 ctermfg=247  gui=BOLD cterm=BOLD
hi Comment      guifg=#AAAAAA ctermfg=248  gui=ITALIC cterm=NONE
hi Constant     guifg=#177F80 ctermfg=30   gui=NONE cterm=NONE
hi String       guifg=#D81745 ctermfg=161  gui=NONE cterm=NONE
hi Function     guifg=#990000 ctermfg=88   gui=BOLD cterm=BOLD
hi Statement    guifg=#000000 ctermfg=16   gui=BOLD cterm=BOLD
hi Type         guifg=#445588 ctermfg=60   gui=BOLD cterm=BOLD
hi Number       guifg=#1C9898 ctermfg=30   gui=NONE cterm=NONE
hi Todo         guifg=#FFFFFF ctermfg=231  guibg=#990000 ctermbg=88   gui=BOLD cterm=BOLD
hi Special      guifg=#159828 ctermfg=28   gui=BOLD cterm=BOLD
hi rubySymbol   guifg=#960B73 ctermfg=89   gui=NONE cterm=NONE
hi Error        guifg=#F8F8FF ctermfg=231  guibg=#FF1100 ctermbg=196  gui=NONE cterm=NONE
hi Todo         guifg=#F8F8FF ctermfg=231  guibg=#FF1100 ctermbg=196  gui=UNDERLINE cterm=UNDERLINE
hi Label        guifg=#000000 ctermfg=16   gui=BOLD cterm=BOLD
hi StorageClass guifg=#000000 ctermfg=16   gui=BOLD cterm=BOLD
hi Structure    guifg=#000000 ctermfg=16   gui=BOLD cterm=BOLD
hi TypeDef      guifg=#000000 ctermfg=16   gui=BOLD cterm=BOLD
hi WildMenu     guifg=#7FBDFF ctermfg=111  guibg=#425C78 ctermbg=60   gui=NONE cterm=NONE
hi Pmenu        guifg=#FFFFFF ctermfg=231  guibg=#808080 ctermbg=244  gui=BOLD cterm=BOLD
hi PmenuSel     guifg=#000000 ctermfg=16   guibg=#CDCDFD ctermbg=189  gui=ITALIC cterm=NONE
hi PmenuSbar    guifg=#444444 ctermfg=238  guibg=#000000 ctermbg=16   gui=NONE cterm=NONE
hi PmenuThumb   guifg=#AAAAAA ctermfg=248  guibg=#AAAAAA ctermbg=248  gui=NONE cterm=NONE
hi TabLine      guifg=#404040 ctermfg=238  guibg=#DDDDDD ctermbg=253  gui=NONE cterm=NONE
hi TabLineFill  guifg=#404040 ctermfg=238  guibg=#DDDDDD ctermbg=253  gui=NONE cterm=NONE
hi TabLineSel   guifg=#404040 ctermfg=238  gui=BOLD cterm=BOLD
hi cucumberTags guifg=#333333 ctermfg=236  guibg=#FFFF66 ctermbg=227  gui=BOLD cterm=BOLD
hi htmlTagN     gui=BOLD cterm=BOLD
hi Cursor       guifg=#F8F8FF ctermfg=231  guibg=#444454 ctermbg=238  gui=NONE cterm=NONE
hi CursorLine   guibg=#D8D8DD ctermbg=253  gui=NONE cterm=NONE
hi CursorColumn guibg=#D8D8DD ctermbg=253  gui=NONE cterm=NONE

hi link rubyStringDelimiter String
=======
" Converted from Textmate theme Github using Coloration v0.3.2 (http://github.com/sickill/coloration)

set background=dark
highlight clear

if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Github"

hi Cursor ctermfg=NONE ctermbg=59 cterm=NONE guifg=NONE guibg=#615649 gui=NONE
hi Visual ctermfg=NONE ctermbg=152 cterm=NONE guifg=NONE guibg=#afc4da gui=NONE
hi CursorLine ctermfg=NONE ctermbg=231 cterm=NONE guifg=NONE guibg=#eeeeee gui=NONE
hi CursorColumn ctermfg=NONE ctermbg=231 cterm=NONE guifg=NONE guibg=#eeeeee gui=NONE
hi ColorColumn ctermfg=NONE ctermbg=231 cterm=NONE guifg=NONE guibg=#eeeeee gui=NONE
hi LineNr ctermfg=248 ctermbg=231 cterm=NONE guifg=#aaaaaa guibg=#eeeeee gui=NONE
hi VertSplit ctermfg=252 ctermbg=252 cterm=NONE guifg=#cecece guibg=#cecece gui=NONE
hi MatchParen ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi StatusLine ctermfg=240 ctermbg=252 cterm=bold guifg=#555555 guibg=#cecece gui=bold
hi StatusLineNC ctermfg=240 ctermbg=252 cterm=NONE guifg=#555555 guibg=#cecece gui=NONE
hi Pmenu ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi PmenuSel ctermfg=NONE ctermbg=152 cterm=NONE guifg=NONE guibg=#afc4da gui=NONE
hi IncSearch ctermfg=NONE ctermbg=152 cterm=NONE guifg=NONE guibg=#abd5d5 gui=NONE
hi Search ctermfg=NONE ctermbg=152 cterm=NONE guifg=NONE guibg=#abd5d5 gui=NONE
hi Directory ctermfg=61 ctermbg=NONE cterm=NONE guifg=#606aa1 guibg=NONE gui=NONE
hi Folded ctermfg=145 ctermbg=15 cterm=NONE guifg=#b8b6b1 guibg=#ffffff gui=NONE

hi Normal ctermfg=240 ctermbg=15 cterm=NONE guifg=#555555 guibg=#ffffff gui=NONE
hi Boolean ctermfg=61 ctermbg=NONE cterm=NONE guifg=#606aa1 guibg=NONE gui=NONE
hi Character ctermfg=61 ctermbg=NONE cterm=NONE guifg=#606aa1 guibg=NONE gui=NONE
hi Comment ctermfg=145 ctermbg=NONE cterm=NONE guifg=#b8b6b1 guibg=NONE gui=NONE
hi Conditional ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi Constant ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi Define ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi ErrorMsg ctermfg=231 ctermbg=38 cterm=NONE guifg=#f8f8f0 guibg=#00a8c6 gui=NONE
hi WarningMsg ctermfg=231 ctermbg=38 cterm=NONE guifg=#f8f8f0 guibg=#00a8c6 gui=NONE
hi Float ctermfg=161 ctermbg=NONE cterm=NONE guifg=#dd1144 guibg=NONE gui=NONE
hi Function ctermfg=88 ctermbg=NONE cterm=NONE guifg=#990000 guibg=NONE gui=NONE
hi Identifier ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=italic
hi Keyword ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi Label ctermfg=161 ctermbg=NONE cterm=NONE guifg=#dd1144 guibg=NONE gui=NONE
hi NonText ctermfg=59 ctermbg=231 cterm=NONE guifg=#3b3a32 guibg=#f7f7f7 gui=NONE
hi Number ctermfg=161 ctermbg=NONE cterm=NONE guifg=#dd1144 guibg=NONE gui=NONE
hi Operator ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi PreProc ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi Special ctermfg=240 ctermbg=NONE cterm=NONE guifg=#555555 guibg=NONE gui=NONE
hi SpecialKey ctermfg=59 ctermbg=231 cterm=NONE guifg=#3b3a32 guibg=#eeeeee gui=NONE
hi Statement ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi StorageClass ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=italic
hi String ctermfg=161 ctermbg=NONE cterm=NONE guifg=#dd1144 guibg=NONE gui=NONE
hi Tag ctermfg=30 ctermbg=NONE cterm=NONE guifg=#008080 guibg=NONE gui=NONE
hi Title ctermfg=240 ctermbg=NONE cterm=bold guifg=#555555 guibg=NONE gui=bold
hi Todo ctermfg=145 ctermbg=NONE cterm=inverse,bold guifg=#b8b6b1 guibg=NONE gui=inverse,bold
hi Type ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline guifg=NONE guibg=NONE gui=underline
hi rubyClass ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi rubyFunction ctermfg=88 ctermbg=NONE cterm=NONE guifg=#990000 guibg=NONE gui=NONE
hi rubyInterpolationDelimiter ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi rubySymbol ctermfg=61 ctermbg=NONE cterm=NONE guifg=#606aa1 guibg=NONE gui=NONE
hi rubyConstant ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=italic
hi rubyStringDelimiter ctermfg=161 ctermbg=NONE cterm=NONE guifg=#dd1144 guibg=NONE gui=NONE
hi rubyBlockParameter ctermfg=61 ctermbg=NONE cterm=NONE guifg=#606aa1 guibg=NONE gui=italic
hi rubyInstanceVariable ctermfg=30 ctermbg=NONE cterm=NONE guifg=#008080 guibg=NONE gui=NONE
hi rubyInclude ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi rubyGlobalVariable ctermfg=30 ctermbg=NONE cterm=NONE guifg=#008080 guibg=NONE gui=NONE
hi rubyRegexp ctermfg=161 ctermbg=NONE cterm=NONE guifg=#dd1144 guibg=NONE gui=NONE
hi rubyRegexpDelimiter ctermfg=161 ctermbg=NONE cterm=NONE guifg=#dd1144 guibg=NONE gui=NONE
hi rubyEscape ctermfg=61 ctermbg=NONE cterm=NONE guifg=#606aa1 guibg=NONE gui=NONE
hi rubyControl ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi rubyClassVariable ctermfg=30 ctermbg=NONE cterm=NONE guifg=#008080 guibg=NONE gui=NONE
hi rubyOperator ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi rubyException ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=NONE
hi rubyPseudoVariable ctermfg=30 ctermbg=NONE cterm=NONE guifg=#008080 guibg=NONE gui=NONE
hi rubyRailsUserClass ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=italic
hi rubyRailsARAssociationMethod ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=NONE
hi rubyRailsARMethod ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=NONE
hi rubyRailsRenderMethod ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=NONE
hi rubyRailsMethod ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=NONE
hi erubyDelimiter ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi erubyComment ctermfg=145 ctermbg=NONE cterm=NONE guifg=#b8b6b1 guibg=NONE gui=NONE
hi erubyRailsMethod ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=NONE
hi htmlTag ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi htmlEndTag ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi htmlTagName ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi htmlArg ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi htmlSpecialChar ctermfg=61 ctermbg=NONE cterm=NONE guifg=#606aa1 guibg=NONE gui=NONE
hi javaScriptFunction ctermfg=235 ctermbg=NONE cterm=NONE guifg=#222222 guibg=NONE gui=italic
hi javaScriptRailsFunction ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=NONE
hi javaScriptBraces ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi yamlKey ctermfg=30 ctermbg=NONE cterm=NONE guifg=#008080 guibg=NONE gui=NONE
hi yamlAnchor ctermfg=30 ctermbg=NONE cterm=NONE guifg=#008080 guibg=NONE gui=NONE
hi yamlAlias ctermfg=30 ctermbg=NONE cterm=NONE guifg=#008080 guibg=NONE gui=NONE
hi yamlDocumentHeader ctermfg=161 ctermbg=NONE cterm=NONE guifg=#dd1144 guibg=NONE gui=NONE
hi cssURL ctermfg=61 ctermbg=NONE cterm=NONE guifg=#606aa1 guibg=NONE gui=italic
hi cssFunctionName ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=NONE
hi cssColor ctermfg=61 ctermbg=NONE cterm=NONE guifg=#606aa1 guibg=NONE gui=NONE
hi cssPseudoClassId ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=NONE
hi cssClassName ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=NONE
hi cssValueLength ctermfg=161 ctermbg=NONE cterm=NONE guifg=#dd1144 guibg=NONE gui=NONE
hi cssCommonAttr ctermfg=60 ctermbg=NONE cterm=NONE guifg=#445588 guibg=NONE gui=NONE
hi cssBraces ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
>>>>>>> 374d19bbe471d19b4d1b5c6e97b4b37b50892394
